services:
  risk-prediction:
    build: ./app
    ports:
      - "5000:5000" # Expose port 5000 on host and container
    
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333" # Expose port 6333 on host and container
    volumes:
      - ./qdrant_data:/qdrant/storage

  semantic-search:
    build: ./semantic_search
    depends_on:
      - qdrant
    ports:
      - "5001:5001" # Expose port 5001 on host and container
    environment:
      - QDRANT_HOST=qdrant
    command: sh -c "python prepare_data.py && gunicorn --bind 0.0.0.0:5001 main:app"
